name: ea-forum-experiments
channels:
  - defaults
  - conda-forge
dependencies:
  # - cudnn[version='>8.1.0']
  - pip
  - pipreqsnb
  # - cudatoolkit[version='>11.2']
  - python
  - graphviz
  - altair
  - altair_saver
  - scipy
  - umap-learn
  - leidenalg
  - pymorphy2
  - gensim
  - python-dotenv
  - nltk
  - wandb
  - requests
  - igraph
  - pygsp
  - ipywidgets
  - html2text
  - ipykernel
  - numpy
  - pandas
  - seaborn
  - datasets
  - tqdm
  - matplotlib
  # - fasttext
  - transformers