jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/seads-org/ea-forum-experiments.git
  SBERTEmbedding:
    resources:
      instance-type: A4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo/
        pip install -r requirements.txt
        python scripts/data/sbert_embedding.py
      image: paperspace/gradient-base:pt112-tf29-jax0314-py39-20220803
    env:
      WANDB_API_KEY: secret:WANDB_API_KEY
      # SBERT_EMB_MODEL: "n8-all-mpnet-base-v2"
      # SBERT_EMB_BATCH_SIZE: "384"
      SBERT_EMB_MODEL: "all-MiniLM-L12-v2:baseline"
      SBERT_EMB_BATCH_SIZE: "1024"
